/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        bg: {
          DEFAULT: 'rgb(var(--color-bg) / <alpha-value>)',
          elevated: 'rgb(var(--color-bg-elevated) / <alpha-value>)',
          sunken: 'rgb(var(--color-bg-sunken) / <alpha-value>)',
          inverse: 'rgb(var(--color-bg-inverse) / <alpha-value>)',
        },
        border: {
          subtle: 'rgb(var(--color-border-subtle) / <alpha-value>)',
          DEFAULT: 'rgb(var(--color-border) / <alpha-value>)',
          strong: 'rgb(var(--color-border-strong) / <alpha-value>)',
        },
        fg: {
          muted: 'rgb(var(--color-fg-muted) / <alpha-value>)',
          subtle: 'rgb(var(--color-fg-subtle) / <alpha-value>)',
          DEFAULT: 'rgb(var(--color-fg) / <alpha-value>)',
          strong: 'rgb(var(--color-fg-strong) / <alpha-value>)',
          inverse: 'rgb(var(--color-fg-inverse) / <alpha-value>)',
        },
        accent: {
          DEFAULT: 'rgb(var(--color-accent) / <alpha-value>)',
          hover: 'rgb(var(--color-accent-hover) / <alpha-value>)',
          pressed: 'rgb(var(--color-accent-pressed) / <alpha-value>)',
          bg: 'rgb(var(--color-accent-bg) / <alpha-value>)',
          fg: 'rgb(var(--color-accent-fg) / <alpha-value>)',
        },
        verdict: {
          verified: 'rgb(var(--color-verdict-verified) / <alpha-value>)',
          'verified-bg': 'rgb(var(--color-verdict-verified-bg) / <alpha-value>)',
          'mostly-true': 'rgb(var(--color-verdict-mostly-true) / <alpha-value>)',
          'mostly-true-bg': 'rgb(var(--color-verdict-mostly-true-bg) / <alpha-value>)',
          'partially-true': 'rgb(var(--color-verdict-partially-true) / <alpha-value>)',
          'partially-true-bg': 'rgb(var(--color-verdict-partially-true-bg) / <alpha-value>)',
          misleading: 'rgb(var(--color-verdict-misleading) / <alpha-value>)',
          'misleading-bg': 'rgb(var(--color-verdict-misleading-bg) / <alpha-value>)',
          false: 'rgb(var(--color-verdict-false) / <alpha-value>)',
          'false-bg': 'rgb(var(--color-verdict-false-bg) / <alpha-value>)',
          unverifiable: 'rgb(var(--color-verdict-unverifiable) / <alpha-value>)',
          'unverifiable-bg': 'rgb(var(--color-verdict-unverifiable-bg) / <alpha-value>)',
          satire: 'rgb(var(--color-verdict-satire) / <alpha-value>)',
          'satire-bg': 'rgb(var(--color-verdict-satire-bg) / <alpha-value>)',
          'no-claim': 'rgb(var(--color-verdict-no-claim) / <alpha-value>)',
          'no-claim-bg': 'rgb(var(--color-verdict-no-claim-bg) / <alpha-value>)',
        },
        focus: 'rgb(var(--color-focus) / <alpha-value>)',
        selection: 'rgb(var(--color-selection) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      fontSize: {
        '2xs': ['11px', { lineHeight: '14px', letterSpacing: '0.04em' }],
        xs: ['12px', { lineHeight: '16px', letterSpacing: '0.02em' }],
        sm: ['13px', { lineHeight: '18px', letterSpacing: '0.005em' }],
        base: ['15px', { lineHeight: '24px', letterSpacing: '-0.005em' }],
        md: ['16px', { lineHeight: '26px', letterSpacing: '-0.005em' }],
        lg: ['19px', { lineHeight: '28px', letterSpacing: '-0.01em' }],
        xl: ['23px', { lineHeight: '32px', letterSpacing: '-0.015em' }],
        '2xl': ['28px', { lineHeight: '34px', letterSpacing: '-0.015em' }],
        '3xl': ['34px', { lineHeight: '40px', letterSpacing: '-0.02em' }],
        '4xl': ['40px', { lineHeight: '44px', letterSpacing: '-0.025em' }],
        '5xl': ['48px', { lineHeight: '52px', letterSpacing: '-0.028em' }],
        '6xl': ['58px', { lineHeight: '60px', letterSpacing: '-0.03em' }],
        '7xl': ['70px', { lineHeight: '72px', letterSpacing: '-0.03em' }],
        eyebrow: ['13px', { lineHeight: '18px', letterSpacing: '0.06em' }],
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '550',
        bold: '600',
        extrabold: '700',
      },
      maxWidth: {
        prose: '640px',
        content: '1120px',
        wide: '1440px',
        measure: '68ch',
      },
      borderRadius: {
        none: '0',
        sm: '4px',
        DEFAULT: '6px',
        md: '8px',
        lg: '10px',
        xl: '14px',
        '2xl': '20px',
        pill: '9999px',
      },
      transitionTimingFunction: {
        'out-quart': 'cubic-bezier(0.25, 1, 0.5, 1)',
        'in-out-quart': 'cubic-bezier(0.76, 0, 0.24, 1)',
      },
      transitionDuration: {
        micro: '120ms',
        macro: '240ms',
        narrative: '600ms',
      },
      keyframes: {
        'sse-row-pulse': {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '1' },
        },
        'sse-row-arrive': {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'dissent-bar-fill': {
          '0%': { transform: 'scaleX(0)' },
          '100%': { transform: 'scaleX(1)' },
        },
        'caret-blink': {
          '0%, 49%': { opacity: '1' },
          '50%, 100%': { opacity: '0' },
        },
        'ticker-scroll': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        'sse-row-pulse': 'sse-row-pulse 1.6s ease-in-out infinite',
        'sse-row-arrive': 'sse-row-arrive 120ms cubic-bezier(0.25, 1, 0.5, 1) both',
        'dissent-bar-fill': 'dissent-bar-fill 240ms cubic-bezier(0.25, 1, 0.5, 1) both',
        'caret-blink': 'caret-blink 1s steps(2) infinite',
        'ticker-scroll': 'ticker-scroll 90s linear infinite',
      },
    },
  },
  plugins: [],
}
